workspace 'AppBaseWorkSpace'
xcodeproj 'CYLAppBaseFrameWork/CYLAppBaseFrameWork.xcodeproj'
xcodeproj 'CYLAppBaseFrameWork-Demo/CYLAppBaseFrameWork-Demo.xcodeproj'

target 'CYLAppBaseFrameWork-Demo' do
pod 'AFNetworking'
pod 'Masonry'
xcodeproj 'CYLAppBaseFrameWork/CYLAppBaseFrameWork.xcodeproj'
end

target 'CYLAppBaseFrameWork' do
pod 'AFNetworking'
pod 'Masonry'
xcodeproj 'CYLAppBaseFrameWork-Demo/CYLAppBaseFrameWork-Demo.xcodeproj'
end